// nghia
package view;

/**
 *
 * @author nghia
 */
public class dialogThongBaoKetNoi extends javax.swing.JDialog {

    /**
     * Creates new form FormThongBaoKetNoi
     * @param parent
     * @param modal
     * @param error
     */
    public dialogThongBaoKetNoi(java.awt.Frame parent, boolean modal, String error) {
        super(parent, modal);
        initComponents();
        areaThongBao.setText(error);
        overRide();
    }

    private void overRide(){
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaThongBao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Xảy Ra Lỗi");

        areaThongBao.setEditable(false);
        areaThongBao.setColumns(20);
        areaThongBao.setForeground(new java.awt.Color(255, 0, 0));
        areaThongBao.setRows(5);
        areaThongBao.setAutoscrolls(false);
        jScrollPane1.setViewportView(areaThongBao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaThongBao;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
