//nghia
package view;

import valid.MaxLength;
import dao.Dao_NhanVien;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import model.NhanVien;
import valid.Regex;
import valid.Valid;

/**
 *
 * @author nghia
 */
public class formThongTinNV extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinNhanVien
     */
    private NhanVien nv;

    public formThongTinNV() {
        initComponents();
        overRide();
        setDataNV();
    }

    public formThongTinNV(NhanVien nv) {
        initComponents();
        overRide();
        this.nv = nv;
        setDataNV();
    }

    private void setDataNV() {
        textMaNhanVien.setText("" + nv.getMaNV());
        textHo.setText(nv.getHo());
        textTen.setText(nv.getTen());
        textDiaChi.setText(nv.getDiaChi());
        textSDT.setText(nv.getSdt());
        if (nv.isTt_nghi()) {
            checkBoxNghiViec.setSelected(true);
        } else {
            checkBoxNghiViec.setSelected(false);
        }
    }

    public void setNv(NhanVien nv) {
        this.nv = nv;
    }

    public NhanVien getNv() {
        return nv;
    }

    public void nhanVien() {
//        checkBoxNghiViec.setEnabled(false);
    }

    private void overRide() {
        setLocationRelativeTo(null);
        textHo.setEnabled(true);
        textTen.setEnabled(true);
        textSDT.setEnabled(true);
        textDiaChi.setEnabled(true);
        checkBoxNghiViec.setEnabled(true);
        buttonLuu.setEnabled(true);
        setMaxLength();

        HoError.setText("");
        TenError.setText("");
        DiaChiError.setText("");
        SDTError.setText("");
        MKError.setText("");

        MKmoi.setVisible(false);
        labelMatKhau.setVisible(false);
        cbHienMK.setVisible(false);
        MKmoi.setDocument(new MaxLength(30));
    }

    private void setMaxLength() {
        textDiaChi.setDocument(new MaxLength(100));
        textHo.setDocument(new MaxLength(50));
        textSDT.setDocument(new MaxLength(10));
        textTen.setDocument(new MaxLength(30));
    }

    private int isHoValid() {
        if (textHo.getText().trim().equals("")) {
            HoError.setText("Không được trống!");
            return 0;
        } else {
            HoError.setText("");
            return 1;
        }
    }

    private int isTenValid() {
        if (textTen.getText().trim().equals("")) {
            TenError.setText("Không được trống!");
            return 0;
        } else {
            TenError.setText("");
            return 1;
        }
    }

    private int isSDTValid() {
        String sdt = textSDT.getText().trim();
        if (sdt.equals("")) {
            SDTError.setText("Không được trống!");
            return 0;
        } else if (!Valid.isTextValid(sdt, Regex.SDT)) {
            SDTError.setText("0xxxxxxxxx");
            return -1;
        } else {
            SDTError.setText("");
            return 1;
        }
    }

    private int isMatKhauValid() {
        char[] mk = MKmoi.getPassword();
        if (mk.length == 0) {
            MKError.setText("Không được trống!");
            buttonLuu.setEnabled(false);
            return 0; //trống
        } else if (mk.length < 4) {
            MKError.setText("Mật khẩu tối thiểu 4 ký tự");
            buttonLuu.setEnabled(false);
            return -2;
        } else {
            MKError.setText("");
            buttonLuu.setEnabled(true);
            return 1; //hợp lệ
        }
    }

    private boolean isAllValid() {
        if (isHoValid() == 1 && isTenValid() == 1 && isSDTValid() == 1) {
            return true; //nếu đúng định dạng
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textHo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textSDT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textDiaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textMaNhanVien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        checkBoxNghiViec = new javax.swing.JCheckBox();
        SDTError = new javax.swing.JLabel();
        HoError = new javax.swing.JLabel();
        TenError = new javax.swing.JLabel();
        DiaChiError = new javax.swing.JLabel();
        labelMatKhau = new javax.swing.JLabel();
        MKmoi = new javax.swing.JPasswordField();
        MKError = new javax.swing.JLabel();
        cbHienMK = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        buttonLuu = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        buttonThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 280));
        setSize(new java.awt.Dimension(550, 280));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(293, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(531, 250));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Họ Nhân Viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel1, gridBagConstraints);

        textHo.setEnabled(false);
        textHo.setPreferredSize(new java.awt.Dimension(170, 28));
        textHo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textHoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(textHo, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Tên Nhân Viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel2, gridBagConstraints);

        textTen.setEnabled(false);
        textTen.setPreferredSize(new java.awt.Dimension(170, 28));
        textTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textTenKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(textTen, gridBagConstraints);

        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Số Điện Thoại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel3, gridBagConstraints);

        textSDT.setEnabled(false);
        textSDT.setPreferredSize(new java.awt.Dimension(170, 28));
        textSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textSDTKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(textSDT, gridBagConstraints);

        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Địa Chỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel4, gridBagConstraints);

        textDiaChi.setEnabled(false);
        textDiaChi.setPreferredSize(new java.awt.Dimension(170, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(textDiaChi, gridBagConstraints);

        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Mã Nhân Viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel5, gridBagConstraints);

        textMaNhanVien.setEnabled(false);
        textMaNhanVien.setPreferredSize(new java.awt.Dimension(170, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(textMaNhanVien, gridBagConstraints);

        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Trạng Thái Nghỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel6, gridBagConstraints);

        checkBoxNghiViec.setText("Nghỉ Việc");
        checkBoxNghiViec.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(checkBoxNghiViec, gridBagConstraints);

        SDTError.setForeground(new java.awt.Color(255, 0, 0));
        SDTError.setText("jLabel7");
        SDTError.setPreferredSize(new java.awt.Dimension(170, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(SDTError, gridBagConstraints);

        HoError.setForeground(new java.awt.Color(255, 0, 0));
        HoError.setText("jLabel8");
        HoError.setPreferredSize(new java.awt.Dimension(170, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(HoError, gridBagConstraints);

        TenError.setForeground(new java.awt.Color(255, 0, 0));
        TenError.setText("jLabel9");
        TenError.setPreferredSize(new java.awt.Dimension(170, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(TenError, gridBagConstraints);

        DiaChiError.setForeground(new java.awt.Color(255, 0, 0));
        DiaChiError.setText("jLabel10");
        DiaChiError.setPreferredSize(new java.awt.Dimension(170, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        jPanel1.add(DiaChiError, gridBagConstraints);

        labelMatKhau.setForeground(new java.awt.Color(0, 102, 204));
        labelMatKhau.setText("Mật Khẩu Mới");
        labelMatKhau.setMinimumSize(new java.awt.Dimension(75, 28));
        labelMatKhau.setPreferredSize(new java.awt.Dimension(75, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(labelMatKhau, gridBagConstraints);

        MKmoi.setMinimumSize(new java.awt.Dimension(170, 28));
        MKmoi.setPreferredSize(new java.awt.Dimension(170, 28));
        MKmoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MKmoiKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(MKmoi, gridBagConstraints);

        MKError.setForeground(new java.awt.Color(255, 0, 0));
        MKError.setText("jLabel7");
        MKError.setMinimumSize(new java.awt.Dimension(170, 28));
        MKError.setPreferredSize(new java.awt.Dimension(170, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(MKError, gridBagConstraints);

        cbHienMK.setForeground(new java.awt.Color(0, 102, 204));
        cbHienMK.setText("Hiện/Ẩn");
        cbHienMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbHienMKMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(cbHienMK, gridBagConstraints);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));

        buttonLuu.setForeground(new java.awt.Color(0, 102, 204));
        buttonLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/floppy-disk-16.png"))); // NOI18N
        buttonLuu.setText("Lưu");
        buttonLuu.setEnabled(false);
        buttonLuu.setPreferredSize(new java.awt.Dimension(140, 35));
        buttonLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLuuMouseClicked(evt);
            }
        });
        jPanel2.add(buttonLuu);

        btnDoiMatKhau.setForeground(new java.awt.Color(0, 102, 204));
        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset-password-16.png"))); // NOI18N
        btnDoiMatKhau.setText("Tạo Mật Khẩu");
        btnDoiMatKhau.setPreferredSize(new java.awt.Dimension(140, 35));
        btnDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoiMatKhauMouseClicked(evt);
            }
        });
        jPanel2.add(btnDoiMatKhau);

        buttonThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit-16.png"))); // NOI18N
        buttonThoat.setText("Thoát");
        buttonThoat.setPreferredSize(new java.awt.Dimension(140, 35));
        buttonThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonThoatMouseClicked(evt);
            }
        });
        jPanel2.add(buttonThoat);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoiMatKhauMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            MKmoi.setVisible(true);
            labelMatKhau.setVisible(true);
            cbHienMK.setVisible(true);
        }
    }//GEN-LAST:event_btnDoiMatKhauMouseClicked

    private void buttonLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLuuMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (isAllValid()) {

                String matKhau;
                if (MKmoi.getPassword().length != 0) {
                    matKhau = new String(MKmoi.getPassword());
                } else {
                    matKhau = "";
                }
                if (Dao_NhanVien.suaNhanVien(nv.getMaNV(), nv.getHo().toUpperCase(), 
                        nv.getTen().toUpperCase(), nv.getDiaChi().toUpperCase(), 
                        nv.getSdt(), nv.isTt_nghi(), matKhau) != 0) {
                    JOptionPane.showMessageDialog(null, "Cập Nhật Thành Công");
                    nv.setHo(textHo.getText().trim().toUpperCase());
                    nv.setTen(textTen.getText().trim().toUpperCase());
                    nv.setDiaChi(textDiaChi.getText().trim().toUpperCase());
                    nv.setSdt(textSDT.getText().trim());
                    nv.setTt_nghi(checkBoxNghiViec.isSelected());
                    setDataNV();
                    panelDSNV.layDSNV(Dao_NhanVien.layDanhSach());
                    panelCaNV.loadComboBoxNhanVien(Dao_NhanVien.layDanhSach());
                } else {
                    JOptionPane.showMessageDialog(null, "", "Cập Nhật Thất Bại", JOptionPane.WARNING_MESSAGE);
                    panelDSNV.layDSNV(Dao_NhanVien.layDanhSach());
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Dữ liệu đã nhập không định dạng!");
            }
        }
    }//GEN-LAST:event_buttonLuuMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        evt.toString();
        panelDSNV.formThongTinNVOpened = false; //đóng
    }//GEN-LAST:event_formWindowClosing

    private void buttonThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonThoatMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            panelDSNV.formThongTinNVOpened = false;//đống
            this.dispose();
        }
    }//GEN-LAST:event_buttonThoatMouseClicked

    private void MKmoiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MKmoiKeyReleased
        // TODO add your handling code here:
        evt.toString();
        isMatKhauValid();
    }//GEN-LAST:event_MKmoiKeyReleased

    private void textSDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSDTKeyReleased
        // TODO add your handling code here:
        evt.toString();
        isSDTValid();
    }//GEN-LAST:event_textSDTKeyReleased

    private void textHoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textHoKeyReleased
        // TODO add your handling code here:
        evt.toString();
        isHoValid();
    }//GEN-LAST:event_textHoKeyReleased

    private void textTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTenKeyReleased
        // TODO add your handling code here:
        evt.toString();
        isTenValid();
    }//GEN-LAST:event_textTenKeyReleased

    private void cbHienMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbHienMKMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (cbHienMK.isSelected()) {
                MKmoi.setEchoChar((char) 0);
            } else {
                MKmoi.setEchoChar('*');
            }
        }
    }//GEN-LAST:event_cbHienMKMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DiaChiError;
    private javax.swing.JLabel HoError;
    private javax.swing.JLabel MKError;
    private javax.swing.JPasswordField MKmoi;
    private javax.swing.JLabel SDTError;
    private javax.swing.JLabel TenError;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton buttonLuu;
    private javax.swing.JButton buttonThoat;
    private javax.swing.JCheckBox cbHienMK;
    private javax.swing.JCheckBox checkBoxNghiViec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelMatKhau;
    private javax.swing.JTextField textDiaChi;
    private javax.swing.JTextField textHo;
    private javax.swing.JTextField textMaNhanVien;
    private javax.swing.JTextField textSDT;
    private javax.swing.JTextField textTen;
    // End of variables declaration//GEN-END:variables
}
