/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.NhanVien;
import model.TaiKhoan;
import dao.Dao_FormNhanVien;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author nguye
 */
public class formDoiMatKhau extends javax.swing.JFrame {
    
    /**
     * Creates new form DoiMatKhau
     */
    public formDoiMatKhau() {
        initComponents();
        String taiKhoan = null;
        taiKhoan = formDangNhap.taiKhoanNV;
        NhanVien nv = new NhanVien();
        nv = new Dao_FormNhanVien().getNhanVienTK(taiKhoan);
        textMaNhanVien.setText(Integer.toString(nv.getMaNV()));   
        buttonLuu.setEnabled(true);
        textMatKhauMoi.setEnabled(true);
        txtMatKhauCu.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        textMaNhanVien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textMatKhauMoi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMatKhauCu = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        buttonLuu = new javax.swing.JButton();
        buttonThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Mã Nhân Viên");

        textMaNhanVien.setEditable(false);
        textMaNhanVien.setEnabled(false);
        textMaNhanVien.setPreferredSize(new java.awt.Dimension(170, 28));
        textMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMaNhanVienActionPerformed(evt);
            }
        });

        jLabel6.setText("Mật khẩu mới");

        textMatKhauMoi.setEnabled(false);
        textMatKhauMoi.setPreferredSize(new java.awt.Dimension(170, 28));
        textMatKhauMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMatKhauMoiActionPerformed(evt);
            }
        });

        jLabel4.setText("Mật khẩu cũ");

        txtMatKhauCu.setEnabled(false);
        txtMatKhauCu.setPreferredSize(new java.awt.Dimension(170, 28));
        txtMatKhauCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauCuActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));

        buttonLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/floppy-disk-16.png"))); // NOI18N
        buttonLuu.setText("Lưu");
        buttonLuu.setEnabled(false);
        buttonLuu.setPreferredSize(new java.awt.Dimension(85, 28));
        buttonLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLuuActionPerformed(evt);
            }
        });
        jPanel2.add(buttonLuu);

        buttonThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit-16.png"))); // NOI18N
        buttonThoat.setText("Thoát");
        buttonThoat.setPreferredSize(new java.awt.Dimension(85, 28));
        buttonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThoatActionPerformed(evt);
            }
        });
        jPanel2.add(buttonThoat);

        jLabel1.setText("Mật khẩu tối thiếu 6 kí tự và tối đa 32 kí tự");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(49, 49, 49)
                                .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMaNhanVienActionPerformed

    private void buttonLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLuuActionPerformed
        // TODO add your handling code here:
        //kiem tra mat khau
        String strTest = textMatKhauMoi.getText().trim();
        String PASSWORD_PATTERN = "^.{4,30}$";
        boolean kiemTraMatKhau = Pattern.matches(PASSWORD_PATTERN, strTest);

        
        
        //
        String taiKhoan = null;
        taiKhoan = formDangNhap.taiKhoanNV;
        NhanVien nv = new Dao_FormNhanVien().getNhanVienTK(taiKhoan);
        TaiKhoan tk = new Dao_FormNhanVien().getTaiKhoan(nv);
        if (txtMatKhauCu.getText().trim().equals(tk.getMAT_KHAU())) {
            if (textMatKhauMoi.getText().trim().equals(txtMatKhauCu.getText().trim())) {
                JOptionPane.showMessageDialog(rootPane, "Mat khau moi trung voi mat khau cu!");
            } 
            else if(kiemTraMatKhau == false)
            {
                JOptionPane.showMessageDialog(rootPane, "Nhap sai dinh dang mat khau, moi nhap lai!");
            }
            else {
                tk.setMAT_KHAU(textMatKhauMoi.getText().trim());
                if (new Dao_FormNhanVien().updateMATKHAUNV(nv, tk)) {
                    JOptionPane.showMessageDialog(rootPane, "Chinh sua thong tin thanh cong!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Khong the chinh sua thong tin! ");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ban nhap sai mat khau !");
        }      
        this.dispose();
    }//GEN-LAST:event_buttonLuuActionPerformed

    private void buttonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonThoatActionPerformed

    private void txtMatKhauCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauCuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauCuActionPerformed

    private void textMatKhauMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMatKhauMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMatKhauMoiActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhau().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLuu;
    private javax.swing.JButton buttonThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textMaNhanVien;
    private javax.swing.JTextField textMatKhauMoi;
    private javax.swing.JTextField txtMatKhauCu;
    // End of variables declaration//GEN-END:variables
}
