//nghia

package view;

import valid.MaxLength;
import dao.Dao_QuayCafe;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.QuayCafe;

/**
 *
 * @author nghia
 */
public class formThemQuay extends javax.swing.JFrame {

    /**
     * Creates new form FormThemQuay
     */
    private DefaultTableModel dtm;
    private QuayCafe quay;

    public formThemQuay() {
        initComponents();
        overRide();
        setMaxLength();

        DuongError.setText("");
        KPError.setText("");
        PhuongError.setText("");
        QuanError.setText("");
        TPError.setText("");
        GiaTienError.setText("");
    }

    private void overRide() {
        this.setLocationRelativeTo(null);
        this.setTitle("Thêm Quầy Cafe");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cbHoatDong.setVisible(false);
        layDSQuay(dao.Dao_QuayCafe.layDSQuay());
        quay = new QuayCafe();
        loadComboBox(Dao_QuayCafe.layDSDuong("khu_pho"), cbbKhuPho);
        loadComboBox(Dao_QuayCafe.layDSDuong("phuong"), cbbPhuong);
        loadComboBox(Dao_QuayCafe.layDSDuong("quan"), cbbQuan);
        loadComboBox(Dao_QuayCafe.layDSDuong("tinh_tp"), cbbThanhPho);
    }

    private void setMaxLength() {
        textDuong.setDocument(new MaxLength(20));
        textGiaTien.setDocument(new MaxLength(15));
    }

    public QuayCafe getQ() {
        return quay;
    }

    public void setQ(QuayCafe q) {
        this.quay = q;
    }

    public void layDSQuay(List<QuayCafe> list) {
        dtm = (DefaultTableModel) tableDSQuay.getModel();
        dtm.setRowCount(0);
//        List<NhanVien> list=dao.dao_NhanVien.layDanhSach();
        list.forEach(q -> {
            dtm.addRow(new Object[]{
                q.getMa(),
                q.getDuong(),
                q.getKp(),
                q.getPhuong(),
                q.getQuan(),
                q.getTp(),
                q.getGiaTien()
            });
        });
    }

    public void loadComboBox(List<String> list, JComboBox cbb) {
        cbb.removeAllItems();

        list.forEach((String q) -> {
            cbb.addItem(q);
        });
        cbb.setSelectedIndex(-1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        buttonReset = new javax.swing.JButton();
        buttonSua = new javax.swing.JButton();
        buttonXoa = new javax.swing.JButton();
        buttonLuu = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        textDuong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbbKhuPho = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbbQuan = new javax.swing.JComboBox<>();
        cbbThanhPho = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbbPhuong = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbHoatDong = new javax.swing.JCheckBox();
        PhuongError = new javax.swing.JLabel();
        TPError = new javax.swing.JLabel();
        DuongError = new javax.swing.JLabel();
        KPError = new javax.swing.JLabel();
        QuanError = new javax.swing.JLabel();
        GiaTienError = new javax.swing.JLabel();
        textGiaTien = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDSQuay = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 100));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(120, 178));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0};
        jPanel3Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0};
        jPanel3.setLayout(jPanel3Layout);

        buttonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh-16.png"))); // NOI18N
        buttonReset.setText("Nhập Lại");
        buttonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonResetMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel3.add(buttonReset, gridBagConstraints);

        buttonSua.setForeground(new java.awt.Color(0, 102, 204));
        buttonSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit-info-16.png"))); // NOI18N
        buttonSua.setText("Sửa");
        buttonSua.setMaximumSize(new java.awt.Dimension(77, 25));
        buttonSua.setMinimumSize(new java.awt.Dimension(77, 25));
        buttonSua.setPreferredSize(new java.awt.Dimension(96, 28));
        buttonSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSuaMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel3.add(buttonSua, gridBagConstraints);

        buttonXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete-16.png"))); // NOI18N
        buttonXoa.setText("Xóa");
        buttonXoa.setMaximumSize(new java.awt.Dimension(77, 25));
        buttonXoa.setMinimumSize(new java.awt.Dimension(77, 25));
        buttonXoa.setPreferredSize(new java.awt.Dimension(96, 28));
        buttonXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonXoaMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel3.add(buttonXoa, gridBagConstraints);

        buttonLuu.setForeground(new java.awt.Color(0, 102, 204));
        buttonLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/floppy-disk-16.png"))); // NOI18N
        buttonLuu.setText("Thêm");
        buttonLuu.setMaximumSize(new java.awt.Dimension(77, 25));
        buttonLuu.setMinimumSize(new java.awt.Dimension(77, 25));
        buttonLuu.setPreferredSize(new java.awt.Dimension(96, 28));
        buttonLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLuuMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel3.add(buttonLuu, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel4Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel4.setLayout(jPanel4Layout);

        textDuong.setMinimumSize(new java.awt.Dimension(133, 34));
        textDuong.setPreferredSize(new java.awt.Dimension(200, 25));
        textDuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textDuongKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(textDuong, gridBagConstraints);

        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Đường Phố");
        jLabel1.setPreferredSize(new java.awt.Dimension(70, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel1, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Khu Phố");
        jLabel2.setPreferredSize(new java.awt.Dimension(70, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel2, gridBagConstraints);

        cbbKhuPho.setEditable(true);
        cbbKhuPho.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(cbbKhuPho, gridBagConstraints);

        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Phường");
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel3, gridBagConstraints);

        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Quận");
        jLabel4.setPreferredSize(new java.awt.Dimension(60, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel4, gridBagConstraints);

        cbbQuan.setEditable(true);
        cbbQuan.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(cbbQuan, gridBagConstraints);

        cbbThanhPho.setEditable(true);
        cbbThanhPho.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(cbbThanhPho, gridBagConstraints);

        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Thành Phố");
        jLabel5.setPreferredSize(new java.awt.Dimension(70, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel5, gridBagConstraints);

        cbbPhuong.setEditable(true);
        cbbPhuong.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(cbbPhuong, gridBagConstraints);

        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Giá Tiền");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel6, gridBagConstraints);

        cbHoatDong.setForeground(new java.awt.Color(0, 102, 204));
        cbHoatDong.setText("Còn Sử Dụng");
        cbHoatDong.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(cbHoatDong, gridBagConstraints);

        PhuongError.setForeground(new java.awt.Color(255, 0, 0));
        PhuongError.setText("jLabel7");
        PhuongError.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(PhuongError, gridBagConstraints);

        TPError.setForeground(new java.awt.Color(255, 0, 0));
        TPError.setText("jLabel8");
        TPError.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(TPError, gridBagConstraints);

        DuongError.setForeground(new java.awt.Color(255, 0, 0));
        DuongError.setText("jLabel9");
        DuongError.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(DuongError, gridBagConstraints);

        KPError.setForeground(new java.awt.Color(255, 0, 0));
        KPError.setText("jLabel10");
        KPError.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(KPError, gridBagConstraints);

        QuanError.setForeground(new java.awt.Color(255, 0, 0));
        QuanError.setText("jLabel11");
        QuanError.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(QuanError, gridBagConstraints);

        GiaTienError.setForeground(new java.awt.Color(255, 0, 0));
        GiaTienError.setText("jLabel12");
        GiaTienError.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(GiaTienError, gridBagConstraints);

        textGiaTien.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###############"))));
        textGiaTien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textGiaTienKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(textGiaTien, gridBagConstraints);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        jPanel2.setMinimumSize(new java.awt.Dimension(500, 100));

        tableDSQuay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Đường Phố", "Khu Phố", "Phường", "Quận", "Tỉnh/Thành Phố", "Giá Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDSQuay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDSQuayMouseClicked(evt);
            }
        });
        tableDSQuay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableDSQuayKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableDSQuay);
        if (tableDSQuay.getColumnModel().getColumnCount() > 0) {
            tableDSQuay.getColumnModel().getColumn(0).setMinWidth(50);
            tableDSQuay.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableDSQuay.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetForm() {
        textDuong.setText("");
        textGiaTien.setText("");
        cbbKhuPho.setSelectedIndex(-1);
        cbbPhuong.setSelectedIndex(-1);
        cbbQuan.setSelectedIndex(-1);
        cbbThanhPho.setSelectedIndex(-1);
        cbHoatDong.setVisible(false);
        tableDSQuay.clearSelection();
        buttonLuu.setEnabled(true);
    }

    private void layDuLieuBang(int i) {
        System.out.println("trong hàm lấy đữ liệu từ bảng");
        int ma = (int) tableDSQuay.getValueAt(i, 0);
        String duong = (String) tableDSQuay.getValueAt(i, 1);
        String kp = (String) tableDSQuay.getValueAt(i, 2);
        String phuong = (String) tableDSQuay.getValueAt(i, 3);
        String quan = (String) tableDSQuay.getValueAt(i, 4);
        String tp = (String) tableDSQuay.getValueAt(i, 5);
        int giaTien = (int) tableDSQuay.getValueAt(i, 6);
        boolean tt_hd = true;
        quay.setMa(ma);
//        q.setDuong(duong);
//        q.setKp(kp);
//        q.setPhuong(phuong);
//        q.setQuan(quan);
//        q.setTp(tp);
//        q.setTt_hd(tt_hd);
//        q.setGiaTien(giaTien);

        textDuong.setText(duong);
        textGiaTien.setText("" + giaTien);
        cbbKhuPho.setSelectedItem(kp);
        cbbPhuong.setSelectedItem(phuong);
        cbbQuan.setSelectedItem(quan);
        cbbThanhPho.setSelectedItem(tp);
        cbHoatDong.setVisible(true);
        cbHoatDong.setSelected(tt_hd);

//        textDuong.setEditable(false);
//        textGiaTien.setEditable(false);
//        cbbKhuPho.setEditable(false);
//        cbbPhuong.setEditable(false);
//        cbbQuan.setEditable(false);
//        cbbThanhPho.setEditable(false);
//        cbHoatDong.setEnabled(false);
    }

    private int isDuongValid() {
        if (textDuong.getText().trim().equals("")) {
            DuongError.setText("Không được trống!");
            return 0;
        } else {
            DuongError.setText("");
            return 1;
        }
    }

    private int isKPValid() {
        if (cbbKhuPho.getSelectedItem() == null) {
            KPError.setText("Không được trống!");
            return 0;
        } else {
            KPError.setText("");
            return 1;
        }
    }

    private int isPhuongValid() {
        if (cbbPhuong.getSelectedItem() == null) {
            PhuongError.setText("Không được trống!");
            return 0;
        } else {
            PhuongError.setText("");
            return 1;
        }
    }

    private int isQuanValid() {
        if (cbbQuan.getSelectedItem() == null) {
            QuanError.setText("Không được trống!");
            return 0;
        } else {
            QuanError.setText("");
            return 1;
        }
    }

    private int isTPValid() {
        if (cbbThanhPho.getSelectedItem() == null) {
            TPError.setText("Không được trống!");
            return 0;
        } else {
            TPError.setText("");
            return 1;
        }
    }

    private int isGiaTienValid() {
        if (textGiaTien.getText().trim().equals("")) {
            GiaTienError.setText("Không được trống!");
            return 0;
        } else {
            GiaTienError.setText("");
            return 1;
        }
    }

    private boolean isAllValid() {
        if (isDuongValid() == 1 && isKPValid() == 1 && isPhuongValid() == 1 && isQuanValid() == 1
                && isTPValid() == 1 && isGiaTienValid() == 1) {
            return true; // true nếu đúng định dạng
        } else {
            return false;
        }
    }

    private void buttonResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResetMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            resetForm();
        }
    }//GEN-LAST:event_buttonResetMouseClicked

    private void buttonLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLuuMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (buttonLuu.isEnabled()) {
                if (isAllValid()) {
                    String duong = textDuong.getText().trim().toUpperCase();
                    String kp = cbbKhuPho.getSelectedItem().toString();
                    String phuong = cbbPhuong.getSelectedItem().toString().toUpperCase();
                    String quan = cbbQuan.getSelectedItem().toString().toUpperCase();
                    String tp = cbbThanhPho.getSelectedItem().toString().toUpperCase();
                    int giaTien = Integer.parseInt(textGiaTien.getText().trim());

                    if (!Dao_QuayCafe.daTonTai(duong, kp, phuong, quan, tp)) {
                        if (Dao_QuayCafe.themQuay(duong, kp, phuong, quan, tp, giaTien) != 0) {
                            layDSQuay(Dao_QuayCafe.layDSQuay());
                            JOptionPane.showMessageDialog(rootPane, "Thêm Thành Công!");
                            panelCaNV.loadComboBoxQuay(Dao_QuayCafe.layDSQuay());
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Thêm Thất Bại!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Quầy này đã tồn tại!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Dữ liệu đã nhập không đúng!");
                }
            }
        }
    }//GEN-LAST:event_buttonLuuMouseClicked

    private void buttonSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSuaMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
//            textDuong.setEditable(true);
//            textGiaTien.setEditable(true);
//            cbbKhuPho.setEditable(true);
//            cbbPhuong.setEditable(true);
//            cbbQuan.setEditable(true);
//            cbbThanhPho.setEditable(true);
//            cbHoatDong.setEnabled(true);

//            if (cbHoatDong.isVisible() == false) {
//                cbHoatDong.setVisible(true);
//                cbHoatDong.setSelected(true);
//            }
            int i = tableDSQuay.getSelectedRow();
            if (i != -1) {
                if (isAllValid()) {
                    String duong = textDuong.getText().trim().toUpperCase();
                    String kp = cbbKhuPho.getSelectedItem().toString().toUpperCase();
                    String phuong = cbbPhuong.getSelectedItem().toString().toUpperCase();
                    String quan = cbbQuan.getSelectedItem().toString().toUpperCase();
                    String tp = cbbThanhPho.getSelectedItem().toString().toUpperCase();
                    int giaTien = Integer.parseInt(textGiaTien.getText().trim());

                    if (Dao_QuayCafe.suaQuay(quay.getMa(), duong, kp, phuong, quan, tp, giaTien, cbHoatDong.isSelected()) != 0) {
                        layDSQuay(Dao_QuayCafe.layDSQuay());
                        panelCaNV.loadComboBoxQuay(Dao_QuayCafe.layDSQuay());
                        JOptionPane.showMessageDialog(rootPane, "Cập Nhật Thành Công!");
                        buttonResetMouseClicked(evt);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Cập Nhật Thất Bại!");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Dữ liệu đã nhập không đúng!");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Chưa Có Dòng Nào Được Chọn");
            }
        }

    }//GEN-LAST:event_buttonSuaMouseClicked

    private void tableDSQuayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableDSQuayKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            tableDSQuay.clearSelection();
            resetForm();
        }
    }//GEN-LAST:event_tableDSQuayKeyPressed

    private void buttonXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXoaMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            System.out.println("xóa click");
            int i = tableDSQuay.getSelectedRow();
            if (i != -1) {
                int ma = (int) tableDSQuay.getValueAt(i, 0);
                int option;
                option = JOptionPane.showConfirmDialog(rootPane, "Bạn Có Muốn Xóa Không?",
                        "Xóa Quầy", JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    if (Dao_QuayCafe.xoaQuay(ma) != 0) {
                        layDSQuay(Dao_QuayCafe.layDSQuay());
                        resetForm();
                        panelCaNV.loadComboBoxQuay(Dao_QuayCafe.layDSQuay());
                        JOptionPane.showMessageDialog(rootPane, "Xóa Thành Công!");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Xóa Thất Bại!");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Chưa Có Dòng Nào Được Chọn");
            }
        }
    }//GEN-LAST:event_buttonXoaMouseClicked

    private void tableDSQuayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDSQuayMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            System.out.println("table click");
            int i = tableDSQuay.getSelectedRow();
            if (i != -1) {
                layDuLieuBang(i);
                buttonLuu.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tableDSQuayMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        evt.toString();
        panelCaNV.formThemQuayOpened = false; //đóng
    }//GEN-LAST:event_formWindowClosing

    private void textDuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDuongKeyReleased
        // TODO add your handling code here:
        evt.toString();
        isDuongValid();
    }//GEN-LAST:event_textDuongKeyReleased

    private void textGiaTienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textGiaTienKeyReleased
        // TODO add your handling code here:
        evt.toString();
        isGiaTienValid();
    }//GEN-LAST:event_textGiaTienKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DuongError;
    private javax.swing.JLabel GiaTienError;
    private javax.swing.JLabel KPError;
    private javax.swing.JLabel PhuongError;
    private javax.swing.JLabel QuanError;
    private javax.swing.JLabel TPError;
    private javax.swing.JButton buttonLuu;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonSua;
    private javax.swing.JButton buttonXoa;
    private javax.swing.JCheckBox cbHoatDong;
    private javax.swing.JComboBox<String> cbbKhuPho;
    private javax.swing.JComboBox<String> cbbPhuong;
    private javax.swing.JComboBox<String> cbbQuan;
    private javax.swing.JComboBox<String> cbbThanhPho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDSQuay;
    private javax.swing.JTextField textDuong;
    private javax.swing.JFormattedTextField textGiaTien;
    // End of variables declaration//GEN-END:variables
}
