/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.MouseEvent;

/**
 *
 * @author nguye
 */
public class formTTQL extends javax.swing.JFrame {

    /**
     * Creates new form formTTQL
     */
    public formTTQL() {
        initComponents();
    }

    public void thongTin() {
        textTen.setEnabled(true);
        textHo.setEnabled(true);
        textDiaChi.setEnabled(true);
        textSDT.setEnabled(true);

        textTen.setEditable(false);
        textHo.setEditable(false);
        textDiaChi.setEditable(false);
        textSDT.setEditable(false);
    }

    public void matKhau(boolean visable, boolean editable) {
        labelMKMoi.setVisible(visable);
        labelMatKhauCu.setVisible(visable);
        labelXacNhan.setVisible(visable);
        pwMKCu.setVisible(visable);
        pwMKMoi.setVisible(visable);
        pwXN.setVisible(visable);
        cbHienMK.setVisible(visable);

        if (visable) {
            pwMKCu.setEditable(editable);
            pwMKMoi.setEditable(editable);
            pwXN.setEditable(editable);
            cbHienMK.setEnabled(editable);
        }

    }
    
    public void nhanVien() {
        thongTin();
        matKhau(false, false);
        button();
    }
    
    public void button() {
        buttonChinhSua.setVisible(false);
        buttonLuu.setVisible(false);
        btnDoiMatKhau.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textHo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textDiaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textSDT = new javax.swing.JTextField();
        labelMKMoi = new javax.swing.JLabel();
        pwMKMoi = new javax.swing.JPasswordField();
        labelXacNhan = new javax.swing.JLabel();
        pwXN = new javax.swing.JPasswordField();
        cbHienMK = new javax.swing.JCheckBox();
        labelMatKhauCu = new javax.swing.JLabel();
        pwMKCu = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        buttonLuu = new javax.swing.JButton();
        buttonChinhSua = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        buttonThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setMinimumSize(new java.awt.Dimension(300, 250));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Mã Quản Lý");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 25, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        jTextField1.setEnabled(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 157;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 5, 0, 0);
        jPanel2.add(jTextField1, gridBagConstraints);

        jLabel2.setText("Họ Quản Lý");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        textHo.setText("Họ Quản Lý");
        textHo.setEnabled(false);
        textHo.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 157;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel2.add(textHo, gridBagConstraints);

        jLabel3.setText("Tên Quản Lý");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        textTen.setEnabled(false);
        textTen.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 157;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel2.add(textTen, gridBagConstraints);

        jLabel4.setText("Địa Chỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 0, 0);
        jPanel2.add(jLabel4, gridBagConstraints);

        textDiaChi.setEnabled(false);
        textDiaChi.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 157;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel2.add(textDiaChi, gridBagConstraints);

        jLabel5.setText("Số Điện Thoại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 40, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        textSDT.setEnabled(false);
        textSDT.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 157;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 40, 0);
        jPanel2.add(textSDT, gridBagConstraints);

        labelMKMoi.setText("Mật Khẩu Mới");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 21, 0, 0);
        jPanel2.add(labelMKMoi, gridBagConstraints);

        pwMKMoi.setEnabled(false);
        pwMKMoi.setPreferredSize(new java.awt.Dimension(120, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 25);
        jPanel2.add(pwMKMoi, gridBagConstraints);

        labelXacNhan.setText("Xác Nhận Mật Khẩu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 5, 0, 0);
        jPanel2.add(labelXacNhan, gridBagConstraints);

        pwXN.setEnabled(false);
        pwXN.setPreferredSize(new java.awt.Dimension(120, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 25);
        jPanel2.add(pwXN, gridBagConstraints);

        cbHienMK.setText("Hiện Mật Khẩu");
        cbHienMK.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 5, 0, 0);
        jPanel2.add(cbHienMK, gridBagConstraints);

        labelMatKhauCu.setText("Mật Khẩu Cũ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(47, 23, 0, 0);
        jPanel2.add(labelMatKhauCu, gridBagConstraints);

        pwMKCu.setEnabled(false);
        pwMKCu.setPreferredSize(new java.awt.Dimension(120, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 5, 0, 25);
        jPanel2.add(pwMKCu, gridBagConstraints);

        jPanel1.setMinimumSize(new java.awt.Dimension(300, 48));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        buttonLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/floppy-disk-16.png"))); // NOI18N
        buttonLuu.setText("Lưu");
        buttonLuu.setEnabled(false);
        buttonLuu.setPreferredSize(new java.awt.Dimension(110, 30));
        jPanel1.add(buttonLuu);

        buttonChinhSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit-info-16.png"))); // NOI18N
        buttonChinhSua.setText("Chỉnh Sửa");
        buttonChinhSua.setPreferredSize(new java.awt.Dimension(110, 30));
        buttonChinhSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonChinhSuaMouseClicked(evt);
            }
        });
        jPanel1.add(buttonChinhSua);

        btnDoiMatKhau.setText("Đổi Mật Khẩu");
        btnDoiMatKhau.setPreferredSize(new java.awt.Dimension(125, 30));
        btnDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoiMatKhauMouseClicked(evt);
            }
        });
        jPanel1.add(btnDoiMatKhau);

        buttonThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit-16.png"))); // NOI18N
        buttonThoat.setText("Thoát");
        buttonThoat.setPreferredSize(new java.awt.Dimension(110, 30));
        buttonThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonThoatMouseClicked(evt);
            }
        });
        jPanel1.add(buttonThoat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChinhSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonChinhSuaMouseClicked
        // TODO add your handling code here:
        buttonLuu.setEnabled(true);
        textHo.setEnabled(true);
        textTen.setEnabled(true);
        textDiaChi.setEnabled(true);
        textSDT.setEnabled(true);
    }//GEN-LAST:event_buttonChinhSuaMouseClicked

    private void btnDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoiMatKhauMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            System.out.println("doi mat khau");
            matKhau(true, true);
        }
    }//GEN-LAST:event_btnDoiMatKhauMouseClicked

    private void buttonThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonThoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonThoatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formTTQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formTTQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formTTQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formTTQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formTTQL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton buttonChinhSua;
    private javax.swing.JButton buttonLuu;
    private javax.swing.JButton buttonThoat;
    private javax.swing.JCheckBox cbHienMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelMKMoi;
    private javax.swing.JLabel labelMatKhauCu;
    private javax.swing.JLabel labelXacNhan;
    private javax.swing.JPasswordField pwMKCu;
    private javax.swing.JPasswordField pwMKMoi;
    private javax.swing.JPasswordField pwXN;
    private javax.swing.JTextField textDiaChi;
    private javax.swing.JTextField textHo;
    private javax.swing.JTextField textSDT;
    private javax.swing.JTextField textTen;
    // End of variables declaration//GEN-END:variables
}
