//nghia

package view;

import valid.MaxLength;
import dao.Dao_ThucDon;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ThucDon;
import valid.Regex;
import valid.Valid;

/**
 *
 * @author nghia
 */
public class panelDSTD extends javax.swing.JPanel {

    /**
     * Creates new form panelDSTD
     */
    private DefaultTableModel dtm;
    private ThucDon td;

    public panelDSTD() {
        initComponents();
        tableDSTD.getTableHeader().setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));
        layDSTD(Dao_ThucDon.layDSTD());
        td = new ThucDon();
        setMaxLength();
    }

    private void setMaxLength() {
        txtTenDoUong.setDocument(new MaxLength(40));
        txtGiaTien.setDocument(new MaxLength(6));
    }

    public ThucDon getTd() {
        return td;
    }

    public void setTd(ThucDon td) {
        this.td = td;
    }

    private void layDSTD(List<ThucDon> list) {
        dtm = (DefaultTableModel) tableDSTD.getModel();
        dtm.setRowCount(0);
        list.forEach(td -> {
            dtm.addRow(new Object[]{
                td.getId(),
                td.getTen(),
                td.getGia()
            });
        });
    }

    private int isTenDoUongValid() {
        if (txtTenDoUong.getText().trim().equals("")) {
            return 0;
        } else {
            return 1;
        }
    }

    private int isGiaTienValid() {
        String giaTien = txtGiaTien.getText().trim();
        if (giaTien.equals("")) {
            return 0;
        } else if (!Valid.isTextValid(giaTien, Regex.NUMBER)) {
            return -1;
        } else {
            return 1;
        }
    }

    private boolean isAllValid() {
        if (isTenDoUongValid() == 1 && isGiaTienValid() == 1) {
            return true;
        } else if (isTenDoUongValid() == 0) {
            JOptionPane.showMessageDialog(this, "Tên đồ uống không được trống!");
            return false;
        } else if (isGiaTienValid() == 0) {
            JOptionPane.showMessageDialog(this, "Chưa nhập giá tiền!");
            return false;
        }else if (isGiaTienValid() == -1) {
            JOptionPane.showMessageDialog(null, "Tiền phải là 1 số");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenDoUong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGiaTien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDSTD = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        buttonSuaTD = new javax.swing.JButton();
        buttonXoaTD = new javax.swing.JButton();
        buttonResetTD = new javax.swing.JButton();
        buttonThemTD = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel4.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 80));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thông Tin Thực Đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel13.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel13.setPreferredSize(new java.awt.Dimension(400, 80));
        java.awt.GridBagLayout jPanel13Layout = new java.awt.GridBagLayout();
        jPanel13Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        jPanel13Layout.rowHeights = new int[] {0, 5, 0};
        jPanel13.setLayout(jPanel13Layout);

        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Tên Đồ Uống");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel13.add(jLabel1, gridBagConstraints);

        txtTenDoUong.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel13.add(txtTenDoUong, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Giá Tiền");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel13.add(jLabel2, gridBagConstraints);

        txtGiaTien.setPreferredSize(new java.awt.Dimension(150, 28));
        jPanel13.add(txtGiaTien, new java.awt.GridBagConstraints());

        jLabel3.setText("VNĐ");
        jPanel13.add(jLabel3, new java.awt.GridBagConstraints());

        jPanel4.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jPanel14.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel14.setPreferredSize(new java.awt.Dimension(400, 80));

        tableDSTD.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableDSTD.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        tableDSTD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã", "Tên Đồ Uống", "Giá Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDSTD.setRowHeight(18);
        tableDSTD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDSTDMouseClicked(evt);
            }
        });
        tableDSTD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableDSTDKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableDSTD);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel14, java.awt.BorderLayout.CENTER);

        add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        buttonSuaTD.setForeground(new java.awt.Color(0, 102, 204));
        buttonSuaTD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit-info-16.png"))); // NOI18N
        buttonSuaTD.setText("Sửa");
        buttonSuaTD.setPreferredSize(new java.awt.Dimension(80, 40));
        buttonSuaTD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSuaTDMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE_LEADING;
        jPanel3.add(buttonSuaTD, gridBagConstraints);

        buttonXoaTD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete-16.png"))); // NOI18N
        buttonXoaTD.setText("Xóa");
        buttonXoaTD.setPreferredSize(new java.awt.Dimension(80, 40));
        buttonXoaTD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonXoaTDMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel3.add(buttonXoaTD, gridBagConstraints);

        buttonResetTD.setForeground(new java.awt.Color(0, 102, 204));
        buttonResetTD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh-16.png"))); // NOI18N
        buttonResetTD.setText("Mới");
        buttonResetTD.setPreferredSize(new java.awt.Dimension(80, 40));
        buttonResetTD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonResetTDMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel3.add(buttonResetTD, gridBagConstraints);

        buttonThemTD.setForeground(new java.awt.Color(0, 102, 204));
        buttonThemTD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/floppy-disk-16.png"))); // NOI18N
        buttonThemTD.setText("Thêm");
        buttonThemTD.setPreferredSize(new java.awt.Dimension(80, 40));
        buttonThemTD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonThemTDMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        jPanel3.add(buttonThemTD, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonThemTDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonThemTDMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (isAllValid()) {
                if (!Dao_ThucDon.daTonTai(txtTenDoUong.getText().trim().toUpperCase())) {
                    if (Dao_ThucDon.themThucDon(txtTenDoUong.getText().trim().toUpperCase(), Integer.parseInt(txtGiaTien.getText().trim())) != 0) {
                        //lấy danh sách
                        layDSTD(Dao_ThucDon.layDSTD());
                        panelLapHD.listDSTD=Dao_ThucDon.layDSTD();
                        panelLapHD.loadComboBoxThucDon(panelLapHD.listDSTD);
                        JOptionPane.showMessageDialog(this, "Thêm Thành Công!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Thêm Thất Bại!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Đồ uống này đã tồn tại!");
                }
            }
        }
    }//GEN-LAST:event_buttonThemTDMouseClicked

    private void layTuBang(int row) {
        String ten = (String) tableDSTD.getValueAt(row, 1);
        int gia = (int) tableDSTD.getValueAt(row, 2);
        int id = (int) tableDSTD.getValueAt(row, 0);
        td.setGia(gia);
        td.setId(id);
        td.setTen(ten);
        txtGiaTien.setText(Integer.toString(gia));
        txtTenDoUong.setText(ten);
    }

    private void tableDSTDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDSTDMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            int row = tableDSTD.getSelectedRow();
            layTuBang(row);
        }
    }//GEN-LAST:event_tableDSTDMouseClicked

    private void buttonSuaTDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSuaTDMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            int row = tableDSTD.getSelectedRow();
            if (row != -1) {
                if (isAllValid()) {
                    int id = (int) tableDSTD.getValueAt(row, 0);
                    String ten = txtTenDoUong.getText().trim().toUpperCase();
                    int gia = Integer.parseInt(txtGiaTien.getText().trim());
                    if (Dao_ThucDon.suaTD(id, ten, gia) != 0) {
                        layDSTD(Dao_ThucDon.layDSTD());
                        panelLapHD.listDSTD=Dao_ThucDon.layDSTD();
                        panelLapHD.loadComboBoxThucDon(panelLapHD.listDSTD);
                        JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công!");
                        reset();
                    } else {
                        JOptionPane.showMessageDialog(this, "Không Thể Cập Nhật!");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Chưa Có Dòng Nào Được Chọn!");
            }
        }
    }//GEN-LAST:event_buttonSuaTDMouseClicked

    private void buttonXoaTDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXoaTDMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            int row = tableDSTD.getSelectedRow();
            if (row != -1) {
                int id = (int) tableDSTD.getValueAt(row, 0);
                if (isAllValid() && Dao_ThucDon.xoaTD(id) > 0 ) {
                    layDSTD(Dao_ThucDon.layDSTD());
                    panelLapHD.listDSTD=Dao_ThucDon.layDSTD();
                        panelLapHD.loadComboBoxThucDon(panelLapHD.listDSTD);
                    JOptionPane.showMessageDialog(this, "Xóa Thành Công!");
                    reset();
                } else {
                    JOptionPane.showMessageDialog(this, "Không Thể Xóa! Đồ uống này đã được bán");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Chưa Có Dòng Nào Được Chọn!");
            }
        }
    }//GEN-LAST:event_buttonXoaTDMouseClicked

    private void buttonResetTDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResetTDMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            reset();
        }
    }//GEN-LAST:event_buttonResetTDMouseClicked

    private void reset() {
        txtGiaTien.setText("");
        txtTenDoUong.setText("");
        tableDSTD.clearSelection();
    }

    private void tableDSTDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableDSTDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            reset();
        }
    }//GEN-LAST:event_tableDSTDKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonResetTD;
    private javax.swing.JButton buttonSuaTD;
    private javax.swing.JButton buttonThemTD;
    private javax.swing.JButton buttonXoaTD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDSTD;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtTenDoUong;
    // End of variables declaration//GEN-END:variables
}
