/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Dao_ThongKeDoanhThu;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.ThongKeChiPhi;
import model.ThongKeDoanhThu;

/**
 *
 * @author nghia
 */
public class panelThongKeDoanhThu extends javax.swing.JPanel {

    /**
     * Creates new form panelThongKeDoanhThu
     */
    private static DefaultTableModel dtm;
    public int i=0;
    public panelThongKeDoanhThu() {
        initComponents();
        tableDoanhThu.getTableHeader().setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));
         layDSDT();
    }
     public void layDSDT(){
        try{
            List<ThongKeDoanhThu> ls=Dao_ThongKeDoanhThu.layDanhSach(null,null);

            dtm = (DefaultTableModel) tableDoanhThu.getModel();
            dtm.setRowCount(0);

            ls.forEach(cp -> {

                dtm.addRow(new Object[]{        
                    i++,
                    cp.getMA_QUAY(),
                    cp.getNGAY(),
                    cp.getDOANHTHU()
                });
            });
        }catch(Exception e){
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel53 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        dateStart = new com.toedter.calendar.JDateChooser();
        jLabel34 = new javax.swing.JLabel();
        dateEnd = new com.toedter.calendar.JDateChooser();
        BtnThongKe = new javax.swing.JButton();
        jPanel54 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tableDoanhThu = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel53.setLayout(new java.awt.GridBagLayout());

        jLabel33.setForeground(new java.awt.Color(0, 102, 204));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel33.setText("Từ Ngày");
        jLabel33.setPreferredSize(new java.awt.Dimension(109, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        jPanel53.add(jLabel33, gridBagConstraints);

        dateStart.setDateFormatString("dd/MM/yyyy");
        dateStart.setMinimumSize(new java.awt.Dimension(20, 20));
        dateStart.setPreferredSize(new java.awt.Dimension(109, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        jPanel53.add(dateStart, gridBagConstraints);

        jLabel34.setForeground(new java.awt.Color(0, 102, 204));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel34.setText("Đến Ngày");
        jLabel34.setPreferredSize(new java.awt.Dimension(109, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        jPanel53.add(jLabel34, gridBagConstraints);

        dateEnd.setDateFormatString("dd/MM/yyyy");
        dateEnd.setPreferredSize(new java.awt.Dimension(109, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        jPanel53.add(dateEnd, gridBagConstraints);

        BtnThongKe.setForeground(new java.awt.Color(0, 51, 255));
        BtnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/analytics-16.png"))); // NOI18N
        BtnThongKe.setText("Thống Kê");
        BtnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThongKeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        jPanel53.add(BtnThongKe, gridBagConstraints);

        add(jPanel53, java.awt.BorderLayout.PAGE_START);

        tableDoanhThu.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        tableDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã Quầy", "Ngày", "Doanh Thu"
            }
        ));
        tableDoanhThu.setRowHeight(18);
        jScrollPane12.setViewportView(tableDoanhThu);

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        add(jPanel54, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThongKeActionPerformed
        // TODO add your handling code here:
        
          java.sql.Date sql_start_date ;
        java.sql.Date sql_end_date;
        try{
            sql_start_date = new java.sql.Date(dateStart.getDate().getTime());
      
        }catch(Exception e){
            sql_start_date=null;
        }
        
         try{
             sql_end_date = new java.sql.Date(dateEnd.getDate().getTime());
        }catch(Exception e){
            sql_end_date=null;
        }
        try{
             i=0;
             List<ThongKeDoanhThu> ls=Dao_ThongKeDoanhThu.layDanhSach(sql_start_date,sql_end_date);
        
            dtm = (DefaultTableModel) tableDoanhThu.getModel();
            dtm.setRowCount(0);

            ls.forEach(cp -> {

                dtm.addRow(new Object[]{        
                    i++,
                    cp.getMA_QUAY(),
                    cp.getNGAY(),
                    cp.getDOANHTHU()
                });
            });
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_BtnThongKeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnThongKe;
    private com.toedter.calendar.JDateChooser dateEnd;
    private com.toedter.calendar.JDateChooser dateStart;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JTable tableDoanhThu;
    // End of variables declaration//GEN-END:variables
}
