/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Dao_ThongKeLoiNhuan;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.ThongKeLoiNhuan;

/**
 *
 * @author nghia
 */
public class panelLoiNhuan extends javax.swing.JPanel {

    /**
     * Creates new form panelLoiNhuan
     */
    private static DefaultTableModel dtm;
    public int i=0;
    public panelLoiNhuan() {
        initComponents();
        tableLoiNhuan.getTableHeader().setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));
        layDSLN();
    }
    //lay danh sach loi nhuan not condition
public void layDSLN(){
        try{
            List<ThongKeLoiNhuan> ls=Dao_ThongKeLoiNhuan.layDanhSach(null,null);

            dtm = (DefaultTableModel) tableLoiNhuan.getModel();
            dtm.setRowCount(0);

            ls.forEach(cp -> {
                dtm.addRow(new Object[]{        
                    i++,
                    cp.getMA_QUAY(),
                    cp.getNGAY(),
                    cp.getLOINHUAN()
                });
            });
        }catch(Exception e){
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel47 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        dateStart = new com.toedter.calendar.JDateChooser();
        jLabel36 = new javax.swing.JLabel();
        dateEnd = new com.toedter.calendar.JDateChooser();
        btnThongKe = new javax.swing.JButton();
        jPanel48 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tableLoiNhuan = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel47.setLayout(new java.awt.GridBagLayout());

        jLabel35.setForeground(new java.awt.Color(0, 102, 204));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel35.setText("Từ Ngày");
        jLabel35.setPreferredSize(new java.awt.Dimension(109, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        jPanel47.add(jLabel35, gridBagConstraints);

        dateStart.setDateFormatString("dd/MM/yyyy");
        dateStart.setMinimumSize(new java.awt.Dimension(20, 20));
        dateStart.setPreferredSize(new java.awt.Dimension(109, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        jPanel47.add(dateStart, gridBagConstraints);

        jLabel36.setForeground(new java.awt.Color(0, 102, 204));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel36.setText("Đến Ngày");
        jLabel36.setPreferredSize(new java.awt.Dimension(109, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        jPanel47.add(jLabel36, gridBagConstraints);

        dateEnd.setDateFormatString("dd/MM/yyyy");
        dateEnd.setPreferredSize(new java.awt.Dimension(109, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        jPanel47.add(dateEnd, gridBagConstraints);

        btnThongKe.setForeground(new java.awt.Color(0, 51, 255));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/analytics-16.png"))); // NOI18N
        btnThongKe.setText("Thống Kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        jPanel47.add(btnThongKe, gridBagConstraints);

        add(jPanel47, java.awt.BorderLayout.PAGE_START);

        tableLoiNhuan.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        tableLoiNhuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã Quầy", "Ngày", "Lợi Nhuận"
            }
        ));
        tableLoiNhuan.setRowHeight(18);
        jScrollPane9.setViewportView(tableLoiNhuan);

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        add(jPanel48, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
  // TODO add your handling code here:   
        java.sql.Date sql_start_date ;
        java.sql.Date sql_end_date;
        try{
            sql_start_date = new java.sql.Date(dateStart.getDate().getTime());
      
        }catch(Exception e){
            sql_start_date=null;
        }
        
         try{
             sql_end_date = new java.sql.Date(dateEnd.getDate().getTime());
        }catch(Exception e){
            sql_end_date=null;
        }
        try{
             i=0;
             List<ThongKeLoiNhuan> ls=Dao_ThongKeLoiNhuan.layDanhSach(sql_start_date,sql_end_date);
        
            dtm = (DefaultTableModel) tableLoiNhuan.getModel();
            dtm.setRowCount(0);

            ls.forEach(cp -> {

                dtm.addRow(new Object[]{        
                    i++,
                    cp.getMA_QUAY(),
                    cp.getNGAY(),
                    cp.getLOINHUAN()
                });
            });
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnThongKeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThongKe;
    private com.toedter.calendar.JDateChooser dateEnd;
    private com.toedter.calendar.JDateChooser dateStart;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable tableLoiNhuan;
    // End of variables declaration//GEN-END:variables
}
