/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Dao_NguyenLieu;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.NguyenLieu;

/**
 *
 * @author nghia
 */
public final class panelNguyenLieu extends javax.swing.JPanel {

    /**
     * Creates new form panelNguyenLieu
     */
    private List<NguyenLieu> lsAllNL;
     private static DefaultTableModel dtm;
     private  int rowSelectedInTable=-1;
      private List<NguyenLieu> lsnguyenlieu;//lay theo ten nguyen lieu
    public panelNguyenLieu() {
        initComponents();
        tableNguyenLieu.getTableHeader().setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));
         dtm = (DefaultTableModel) tableNguyenLieu.getModel();
         dtm.setRowCount(0);
         layDSNL();
         layDSTEN_NGUYEN_LIEU();
    }
    //hien thi nguyen lieu -> table
    private void layDSNL(){
                lsAllNL=Dao_NguyenLieu.layDS();
                this.showDS();
    }
    //show DS nguyen lieu tu list ra table
    private void showDS(){
                 dtm.setRowCount(0);
                if(!lsAllNL.isEmpty()){
                lsAllNL.forEach(cp -> {
                    dtm.addRow(new Object[]{        
                            cp.getMaNL(),
                            cp.getTenNL(),
                            cp.getDonViTinh()
                        });
                    });
                }
    }
    //láy danh sach ten nguyen lieu-> combox
 public void layDSTEN_NGUYEN_LIEU(){
        this.lsnguyenlieu=Dao_NguyenLieu.layDS();
        cbbtimkiem.removeAllItems();
         if(!this.lsnguyenlieu.isEmpty()){
             this.lsnguyenlieu.forEach(p -> {
                 cbbtimkiem.addItem(p.getTenNL());
               });
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel25 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        Them = new javax.swing.JButton();
        jPanel33 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtMaNL = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDVT = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTenNL = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cbbtimkiem = new javax.swing.JComboBox<>();
        btnTimkiem = new javax.swing.JButton();
        jPanel29 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableNguyenLieu = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(400, 300));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm Nguyên Liệu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel25.setMinimumSize(new java.awt.Dimension(420, 125));
        jPanel25.setPreferredSize(new java.awt.Dimension(420, 313));
        jPanel25.setLayout(new java.awt.BorderLayout());

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Nhập Nguyên Liệu");

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel25.add(jPanel30, java.awt.BorderLayout.PAGE_START);

        jPanel31.setLayout(new java.awt.BorderLayout());

        jPanel32.setMinimumSize(new java.awt.Dimension(423, 25));
        jPanel32.setLayout(new java.awt.GridBagLayout());

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete-16.png"))); // NOI18N
        jButton15.setText("Xóa");
        jButton15.setPreferredSize(new java.awt.Dimension(110, 35));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        jPanel32.add(jButton15, gridBagConstraints);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit-info-16.png"))); // NOI18N
        jButton16.setText("Chỉnh Sửa");
        jButton16.setPreferredSize(new java.awt.Dimension(110, 35));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChinhsuaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel32.add(jButton16, gridBagConstraints);

        Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/floppy-disk-16.png"))); // NOI18N
        Them.setText("Thêm");
        Them.setPreferredSize(new java.awt.Dimension(110, 35));
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });
        jPanel32.add(Them, new java.awt.GridBagConstraints());

        jPanel31.add(jPanel32, java.awt.BorderLayout.CENTER);

        jPanel33.setMinimumSize(new java.awt.Dimension(300, 58));
        jPanel33.setPreferredSize(new java.awt.Dimension(300, 158));
        jPanel33.setLayout(new java.awt.GridBagLayout());

        jLabel15.setForeground(new java.awt.Color(0, 102, 204));
        jLabel15.setText("Mã Nguyên Liệu");
        jLabel15.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel33.add(jLabel15, gridBagConstraints);

        txtMaNL.setEditable(false);
        txtMaNL.setMinimumSize(new java.awt.Dimension(100, 19));
        txtMaNL.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel33.add(txtMaNL, gridBagConstraints);

        jLabel16.setForeground(new java.awt.Color(0, 102, 204));
        jLabel16.setText("Đơn Vị Tính");
        jLabel16.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel33.add(jLabel16, gridBagConstraints);

        txtDVT.setMinimumSize(new java.awt.Dimension(100, 19));
        txtDVT.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel33.add(txtDVT, gridBagConstraints);

        jLabel17.setForeground(new java.awt.Color(0, 102, 204));
        jLabel17.setText("Tên Nguyên Liệu");
        jLabel17.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel33.add(jLabel17, gridBagConstraints);

        txtTenNL.setMinimumSize(new java.awt.Dimension(100, 19));
        txtTenNL.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel33.add(txtTenNL, gridBagConstraints);

        jPanel31.add(jPanel33, java.awt.BorderLayout.PAGE_START);

        jPanel25.add(jPanel31, java.awt.BorderLayout.CENTER);

        add(jPanel25);

        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Nguyên Liệu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel26.setLayout(new java.awt.BorderLayout());

        jPanel28.setPreferredSize(new java.awt.Dimension(394, 70));
        jPanel28.setLayout(new java.awt.GridBagLayout());

        jLabel13.setForeground(new java.awt.Color(0, 102, 204));
        jLabel13.setText("Tìm Kiếm Theo Tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel28.add(jLabel13, gridBagConstraints);

        cbbtimkiem.setEditable(true);
        cbbtimkiem.setMinimumSize(new java.awt.Dimension(100, 24));
        cbbtimkiem.setPreferredSize(new java.awt.Dimension(200, 24));
        cbbtimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbtimkiemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 5;
        jPanel28.add(cbbtimkiem, gridBagConstraints);

        btnTimkiem.setForeground(new java.awt.Color(0, 102, 204));
        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/magnifying-glass-16.png"))); // NOI18N
        btnTimkiem.setText("Tìm Kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel28.add(btnTimkiem, gridBagConstraints);

        jPanel26.add(jPanel28, java.awt.BorderLayout.PAGE_START);

        tableNguyenLieu.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        tableNguyenLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Nguyên Liệu", "Tên Nguyên Liệu", "Đơn Vị Tính"
            }
        ));
        tableNguyenLieu.setRowHeight(18);
        tableNguyenLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNguyenLieuMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableNguyenLieu);

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        jPanel26.add(jPanel29, java.awt.BorderLayout.CENTER);

        add(jPanel26);
    }// </editor-fold>//GEN-END:initComponents

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
                String Ma_Nguyen_Lieu= txtMaNL.getText().trim();
                String Ten_NL = txtTenNL.getText().trim();
                String DVT= txtDVT.getText().trim();

                dtm.setRowCount(0);
                 try{
             //kiểm tra diệu diện khác rỗng, mã nguyen liẹu trùng
                if (Dao_NguyenLieu.luuNguyenLieu(Ten_NL, DVT )!=0 ){
                    System.out.println("---Lưu thành công vào CSDL--");
                    txtMaNL.setText("");
                    txtTenNL.setText("");
                    txtDVT.setText("");
                }else{
                    System.out.println("---Không the luu vào CSDL--");
                }
                this.layDSNL();
                }catch(Exception e){
                    System.out.println(e);
                }
                
                
   
    }//GEN-LAST:event_ThemActionPerformed

    private void cbbtimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbtimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbtimkiemActionPerformed
    /**private int isTenNLValid() {
        String TenNL = txtTenNL.getText().trim();
        if (!Valid.isTextValid(TenNL, Regex.W)) {
            return -1;
        }else {
            return 1;
        }
    }
    private boolean isAllValid() {
    if (isTenNLValid() == 1) {
            return true;
    }else if (isTenNLValid() == -1) {
            JOptionPane.showMessageDialog(this, "Tên nguyên liệu chỉ chứa a-zA-Z");
            return false;
    } else {
            return true;
            }
    }*/
    private void ChinhsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChinhsuaActionPerformed
        String Ma_Nguyen_Lieu= txtMaNL.getText().trim();
        String Ten_NL = txtTenNL.getText().trim();
        String DVT= txtDVT.getText().trim();
        
        // giu nguyen getSelected khi nhấn btn Chinh Sua
        try{
            if(tableNguyenLieu.getSelectedRow()!=-1){
                rowSelectedInTable =tableNguyenLieu.getSelectedRow();
            }
        }catch(Exception e){

        }
        if(this.rowSelectedInTable==-1){
            return ;
        }
         NguyenLieu NL=this.lsAllNL.get(rowSelectedInTable);
        if(!Ma_Nguyen_Lieu.equals(NL.getMaNL()+"")){
            System.out.println("MANL khong dc thay doi");
            return ;
        } 
        if(Ten_NL.isEmpty()|| DVT.isEmpty()){
            System.out.println("Khong duoc de trong ");
            return ;
        }
        
        if(Dao_NguyenLieu.suaNL(Ma_Nguyen_Lieu,Ten_NL,DVT)!=0){
            //cap nhat tren list (lsAllNL)
            NL.setTenNL(Ten_NL);
            NL.setDonViTinh(DVT);
            this.showDS();
            
        }
    }//GEN-LAST:event_ChinhsuaActionPerformed

    private void tableNguyenLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNguyenLieuMouseClicked
         try{
        rowSelectedInTable =tableNguyenLieu.getSelectedRow();
        }catch(Exception e){
           this.rowSelectedInTable=-1;
        }
        if(rowSelectedInTable==-1){
            System.out.println("Chon Vao Table");
             txtMaNL.setText("");
            txtTenNL.setText("");
            txtDVT.setText("");
            return ;
        }
        NguyenLieu NL=this.lsAllNL.get(rowSelectedInTable);
        //
         txtMaNL.setText(NL.getMaNL()+"");
        txtTenNL.setText(NL.getTenNL());
        txtDVT.setText(NL.getDonViTinh());
    }//GEN-LAST:event_tableNguyenLieuMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        try{
        rowSelectedInTable =tableNguyenLieu.getSelectedRow();
        }catch(Exception e){
           this.rowSelectedInTable=-1;
        }
        NguyenLieu NL=this.lsAllNL.get(rowSelectedInTable);
        if(rowSelectedInTable==-1){
          
       }else{
           this.lsAllNL.remove(rowSelectedInTable);
           Dao_NguyenLieu.xoaNL(NL.getMaNL());
           this.showDS();
            txtMaNL.setText("");
            txtTenNL.setText("");
            txtDVT.setText("");
       }
    }//GEN-LAST:event_DeleteActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        String TenNguyenLieu=cbbtimkiem.getSelectedItem().toString();
        List<NguyenLieu> ls=Dao_NguyenLieu.layNLTheoTen(TenNguyenLieu);
        lsAllNL=ls;
        this.showDS();
    }//GEN-LAST:event_btnTimkiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Them;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JComboBox<String> cbbtimkiem;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tableNguyenLieu;
    private javax.swing.JTextField txtDVT;
    private javax.swing.JTextField txtMaNL;
    private javax.swing.JTextField txtTenNL;
    // End of variables declaration//GEN-END:variables
}
