/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Dao_ThongKeChiPhi;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.ThongKeChiPhi;

/**
 *
 * @author nghia
 */
public class panelThongKeChiPhi extends javax.swing.JPanel {

    /**
     * Creates new form panelThongKeChiPhi
     */
    private static DefaultTableModel dtm;
    public int i=0;
    public panelThongKeChiPhi() {
        initComponents();
        tableChiPhi.getTableHeader().setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));
        layDSCP();
    }
    public void layDSCP(){
        try{
            List<ThongKeChiPhi> ls=Dao_ThongKeChiPhi.layDanhSach(null,null);

            dtm = (DefaultTableModel) tableChiPhi.getModel();
            dtm.setRowCount(0);

            ls.forEach(cp -> {

                dtm.addRow(new Object[]{        
                    i++,
                    cp.getMA_QUAY(),
                    cp.getNGAY(),
                    cp.getCHIPHI()
                });
            });
        }catch(Exception e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel43 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        dateStart = new com.toedter.calendar.JDateChooser();
        jLabel29 = new javax.swing.JLabel();
        dateEnd = new com.toedter.calendar.JDateChooser();
        BtnThongKe = new javax.swing.JButton();
        jPanel44 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableChiPhi = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel43.setLayout(new java.awt.GridBagLayout());

        jLabel28.setForeground(new java.awt.Color(0, 102, 204));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel28.setText("Từ Ngày");
        jLabel28.setPreferredSize(new java.awt.Dimension(109, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        jPanel43.add(jLabel28, gridBagConstraints);

        dateStart.setDateFormatString("dd/MM/yyyy");
        dateStart.setMinimumSize(new java.awt.Dimension(20, 20));
        dateStart.setPreferredSize(new java.awt.Dimension(109, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        jPanel43.add(dateStart, gridBagConstraints);

        jLabel29.setForeground(new java.awt.Color(0, 102, 204));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel29.setText("Đến Ngày");
        jLabel29.setPreferredSize(new java.awt.Dimension(109, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        jPanel43.add(jLabel29, gridBagConstraints);

        dateEnd.setDateFormatString("dd/MM/yyyy");
        dateEnd.setPreferredSize(new java.awt.Dimension(109, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        jPanel43.add(dateEnd, gridBagConstraints);

        BtnThongKe.setForeground(new java.awt.Color(0, 51, 255));
        BtnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/analytics-16.png"))); // NOI18N
        BtnThongKe.setText("Thống Kê");
        BtnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThongKeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        jPanel43.add(BtnThongKe, gridBagConstraints);

        add(jPanel43, java.awt.BorderLayout.PAGE_START);

        tableChiPhi.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        tableChiPhi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã Quầy", "Ngày", "Chi Phí"
            }
        ));
        tableChiPhi.setRowHeight(18);
        jScrollPane7.setViewportView(tableChiPhi);

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        add(jPanel44, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThongKeActionPerformed
        // TODO add your handling code here:   
        java.sql.Date sql_start_date ;
        java.sql.Date sql_end_date;
        try{
            sql_start_date = new java.sql.Date(dateStart.getDate().getTime());
      
        }catch(Exception e){
            sql_start_date=null;
        }
        
         try{
             sql_end_date = new java.sql.Date(dateEnd.getDate().getTime());
        }catch(Exception e){
            sql_end_date=null;
        }
        try{
             i=0;
             List<ThongKeChiPhi> ls=Dao_ThongKeChiPhi.layDanhSach(sql_start_date,sql_end_date);
        
            dtm = (DefaultTableModel) tableChiPhi.getModel();
            dtm.setRowCount(0);

            ls.forEach(cp -> {

                dtm.addRow(new Object[]{        
                    i++,
                    cp.getMA_QUAY(),
                    cp.getNGAY(),
                    cp.getCHIPHI()
                });
            });
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_BtnThongKeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnThongKe;
    private com.toedter.calendar.JDateChooser dateEnd;
    private com.toedter.calendar.JDateChooser dateStart;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tableChiPhi;
    // End of variables declaration//GEN-END:variables
}
