/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Dao_NhanVien;
import dao.Dao_QuayCafe;
import dao.Dao_PhieuNhap;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;
import model.ThongKePhieuNhap;
import model.QuayCafe;

/**
 *
 * @author nghia
 */
public final class panelDSPN extends javax.swing.JPanel {

    /**
     * Creates new form panelDSPN
     */
    private static DefaultTableModel dtm;

    public panelDSPN() {
        initComponents();
        tableDSPN.getTableHeader().setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 15));
        layDSPN();
        layDSMAQUAY();
        layDSMANV();
    }

    //get all list MA QUAY -> combox
    public void layDSMAQUAY() {
        List<QuayCafe> ls = Dao_QuayCafe.layDSQuay();
        combox_MA_QUAY.removeAllItems();
        combox_MA_QUAY.addItem("");
        if (!ls.isEmpty()) {
            ls.forEach(pn -> {
                combox_MA_QUAY.addItem(
                        pn.getMa()+""
                );
            });
        }

    }

    //get all list MA NHAN VIEN -> combox
    public void layDSMANV() {

        List<NhanVien> ls = Dao_NhanVien.layDanhSach();
        combox_MA_NV.removeAllItems();
        combox_MA_NV.addItem("");
        if (!ls.isEmpty()) {
            ls.forEach(pn -> {
                combox_MA_NV.addItem(
                        String.valueOf(pn.getMaNV()));
            });
        }

    }

    public void layDSPN() {
        //layDanhSach(theo mã quầy ,theo mã nhân viên)
        List<ThongKePhieuNhap> ls = Dao_PhieuNhap.layDanhSachThongKe(null, null);

        dtm = (DefaultTableModel) tableDSPN.getModel();
        dtm.setRowCount(0);
        if (!ls.isEmpty()) {
            ls.forEach(pn -> {

                dtm.addRow(new Object[]{
                    pn.getMA_PHIEU_NHAP(),
                    pn.getNGAY_NHAP(),
                    pn.getMA_NHAN_VIEN(),
                    pn.getMA_QUAY(),
                    pn.getMA_NGUYEN_LIEU(),
                    pn.getSO_LUONG(),
                    pn.getGIA_TIEN()
                });
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel51 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        combox_MA_QUAY = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        combox_MA_NV = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        jPanel52 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tableDSPN = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel51.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel51.setPreferredSize(new java.awt.Dimension(810, 50));

        jLabel31.setForeground(new java.awt.Color(0, 102, 204));
        jLabel31.setText("Theo Mã Quầy");
        jLabel31.setPreferredSize(new java.awt.Dimension(80, 25));
        jPanel51.add(jLabel31);

        combox_MA_QUAY.setEditable(true);
        combox_MA_QUAY.setMaximumSize(new java.awt.Dimension(32767, 20));
        combox_MA_QUAY.setMinimumSize(new java.awt.Dimension(127, 20));
        combox_MA_QUAY.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel51.add(combox_MA_QUAY);

        jLabel32.setForeground(new java.awt.Color(0, 102, 204));
        jLabel32.setText("Theo Mã Nhân Viên");
        jLabel32.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel51.add(jLabel32);

        combox_MA_NV.setEditable(true);
        combox_MA_NV.setMaximumSize(new java.awt.Dimension(32767, 20));
        combox_MA_NV.setMinimumSize(new java.awt.Dimension(127, 20));
        combox_MA_NV.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel51.add(combox_MA_NV);

        btnTimKiem.setForeground(new java.awt.Color(0, 102, 204));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/magnifying-glass-16.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel51.add(btnTimKiem);

        add(jPanel51, java.awt.BorderLayout.PAGE_START);

        tableDSPN.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        tableDSPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Phiếu Nhập", "Ngày Nhập", "Mã Nhân Viên", "Mã Quầy", "Mã Nguyên Liệu", "Số Lượng", "Giá Tiền"
            }
        ));
        tableDSPN.setRowHeight(18);
        jScrollPane10.setViewportView(tableDSPN);

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        );

        add(jPanel52, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String itemMaQuay = null;
        String itemMaNV = null;
        try {
            itemMaQuay = combox_MA_QUAY.getSelectedItem().toString();
            if (itemMaQuay.isEmpty()) {
                itemMaQuay = null;
            }
        } catch (Exception e) {
        }

        try {
            itemMaNV = combox_MA_NV.getSelectedItem().toString();
            if (itemMaNV.isEmpty()) {
                itemMaNV = null;
            }
        } catch (Exception e) {
        }

        System.out.println("quay: " + itemMaQuay + "---MV: " + itemMaNV);
        try {
            List<ThongKePhieuNhap> ls = Dao_PhieuNhap.layDanhSachThongKe(itemMaQuay, itemMaNV);

            dtm = (DefaultTableModel) tableDSPN.getModel();
            dtm.setRowCount(0);

            ls.forEach(pn -> {
                dtm.addRow(new Object[]{
                    pn.getMA_PHIEU_NHAP(),
                    pn.getNGAY_NHAP(),
                    pn.getMA_NHAN_VIEN(),
                    pn.getMA_QUAY(),
                    pn.getMA_NGUYEN_LIEU(),
                    pn.getSO_LUONG(),
                    pn.getGIA_TIEN()
                });
            });
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> combox_MA_NV;
    private javax.swing.JComboBox<String> combox_MA_QUAY;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JTable tableDSPN;
    // End of variables declaration//GEN-END:variables
}
